version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: currency_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Heslo1234.
      POSTGRES_DB: currencyapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: